### ISSUE TITLE
Spot Force Recycling / Broker Crash Disaster Recovery

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq-for-kafka#447]
The core of AutoMQ for Kafka's fault tolerance is:
- Uploading the data in the Delta WAL that has not been uploaded to the object storage => Other nodes can safely read the data of the Stream from the object storage.
- Closing the Stream opened by the corresponding node => Other nodes can open the Stream and recover the Partition.

### Spot Termination
The Controller polls AutoMQ Serverless Component to obtain the nodes that require fault tolerance and invokes Controller#failover(FailoverContext{ nodeId, deltaWALVolumeId }). The Controller records the FailoverContext and initiates the asynchronous fault tolerance process in the background.
P.S. Other types of instance downsizing can also follow the same process to ensure no data is missed during upload.

### Broker Crash
The Controller detects the broker session timeout, considering the Broker node crashed/hanged. First, it retrieves the volume of the corresponding Broker node by calling AutoMQ Serverless Component and then invokes `Controller#failover(FailoverContext{  nodeId,  deltaWALVolumeId })` to initiate the asynchronous fault tolerance process in the background.
High broker loads may lead to incorrect judgment of heartbeat timeouts, so the Broker needs to implement backpressure and load isolation to ensure the stability of routine heartbeat processes.

## Fault Tolerance Process
Upon receiving a fault tolerance request for the Delta WAL (data volume), the Controller records the fault tolerance context FailoverContext in the metadata and triggers the background asynchronous fault tolerance process:

```
FailoverContext {
    nodeId,
    volumeId, // Volume ID
    volumeType, // Type of volume, e.g., whether NVMe reservation can be used
    device, // Mounted volume name; Broker addresses the corresponding block device through the device name
    status, // Status: WAITING || RECOVERING || DONE
    targetNodeId, // Target node responsible for failover
}
```

1. The Controller scans for FailoverContext in the WAITING status.
2. The Controller selects a live node in the cluster with fewer than 16 ongoing failover processes (volume attach limit).
3. The Controller calls AutoMQ Serverless Component `bind(nodeId, volumeId, targetIP)` for volume attach (for nodes without multi-attach support, the old node needs to be power fenced) (If already attached, it must be detached first, and the AS component must be executed by a stateless cloud proxy to avoid consistency issues).
4. The Controller updates FailoverContext{ status = RECOVERING, targetNodeId, device }.
5. The Broker listens for the fault tolerance event and performs the fault tolerance recovery:
   1. Invoke AutoMQ Serverless Component `fence(nodeId, volumeId)` to prevent old node write.
   2. Recovers data from the Delta WAL, retrieves the nodeId and epoch associated with the Delta WAL, along with the data that has not been uploaded.
   3. Uploads the data and closes the stream in the open state for the nodeId.
6. The Broker invokes AutoMQ Serverless Component `delete(nodeId, volumeId)` to delete the volume.
7. The Controller repeats the scan volume and marks the deleted volume's FailoverContex.status to DONE.

In the 5b process, an additional parameter failoverMark = true needs to be carried. The Controller rejects all requests (nodeId, epoch) without the failoverMark = true if it receives the failoverMark, avoiding situations where the original Broker is still sending requests to the Controller despite being falsely dead.

**Comment by superhx** [comment]
AutoScaling#bind(volumeId, targetIP) -> device:
-If the volume doesn't support Multi-Attach: bind operation should first detach the volume from current node and attach it to the targetIp
- If the volume support Multi-Attach: bind operation could directly attach the volume to the targetIp

**Comment by KaimingWan** [comment]
AutoMQ Serverless Component is a dependent command line tool that help AutoMQ Kafka communication with multi cloud' service to support features like autoscaling, failover etc. To support this issue, now AutoMQ Serverless Component support following command:

|  Cloud Resource   | Action  | Instructions |command example |
|  ----  | ----  | ---- | ---- |
| ec2  | addTag | Operate cloud to add tag to ec2 that is used to filter ec2 by kafka nodeID tag. | amq-serverless ec2 addTag -n 1 |
| volume  | addTag |  Operate cloud to add tag to volume that is used to filter volume by first bind nodeID tag. | amq-serverless volume addTag -n 1 |
| volume  | attach |  Operate cloud to attach volume to target node. If the volume is already attached to other node, the serverless command will do detach first | amq-serverless volume attach  -v vol-03e77496d6e279458 -n 2 -d /dev/xvda |
| volume  | delete |  Operate cloud to delete volume. If the volume is already attached to other node, the serverless command will do detach first before delete | amq-serverless volume delete -v vol-03e77496d6e279458 |
| volume  | fence |  Operate cloud to fence volume. May use the following action in different cases. If the volume support multi attach and not support nvme reservation acquire or not support multi attach, serverless component will do power fence(terminate ec2) to avoid dirty write when ec2 exists. If the volume support multi attach and nvme reservation acquire , the serverless component will do nvme reservation acquire in the local node to fence other node's write | amq-serverless volume fence -v vol-03e77496d6e279458 |
| volume  | query |   Get meta info of volume that need failover to other node. Failover may caused by spot instance replacement or self detected broker hang | amq-serverless volume query|

**Comment by KaimingWan** [comment]
Pay attention that although AWS volume describe API not give the real nvme device name, when you use Amazon Linux AMI later than version 2017.09.01, the system will automatically create a symbolic link to the block-device mapping so that AutoMQ Kafka can directlt use the device name returned from aws attach API.

You can find the evidence in aws official document [Amazon EBS and NVMe on Linux instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#identify-nvme-ebs-device)

> For Nitro-based instances, the block device mappings that are specified in the Amazon EC2 console when you are attaching an EBS volume or during AttachVolume or RunInstances API calls are captured in the vendor-specific data field of the NVMe controller identification. With Amazon Linux AMIs later than version 2017.09.01, we provide a udev rule that reads this data and creates a symbolic link to the block-device mapping.
